name: Publish Docker Image

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Debug secrets availability
      run: |
        echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' }}"
        echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' }}"

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: kesertki/whisper:latest